name: Build and Deploy Dioxus App

on:
  push:
    branches:
      - main  # 或 master，根据你的主分支名

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限设置

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build with trunk
        run: trunk build --release --public-url ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages